global:
  scrape_interval: 15s

scrape_configs:
  # Monitoramento do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # LoginHub
  - job_name: 'loginhub-api'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['awlsrv_login_hub_api:3000']